---
- name: filters
  include_tasks: transformSettings.yml
  vars:
    basepath: /opnsense/filter/rule
    name: Firewall Rule

  loop: "{{ opn_filter | default([]) + opn_vlan_filter | default([]) }}"
  when: opn_filter is defined or  opn_vlan_filter is defined
...
