---
# example definition
#
# One-to-one: Firewall A example from https://docs.opnsense.org/manual/how-tos/ipsec-s2s-binat.html
#
# opn_nat_onetoone:
#   - descr: IPsec BINAT
#     settings:
#       - key: interface
#         value: enc0
#       - key: type
#         value: binat
#       - key: external
#         value: '192.168.1.0'
#       - key: source/address
#         value: '10.0.1.0/24'
#       - key: destination/address
#         value: '192.168.2.0/24'


- name: nat - settings
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/{{ item.key }}"
    value: "{{ item.value }}"
    pretty_print: yes
  with_dict: "{{ opn_nat_settings | default([]) }}"

- name: NAT Rule
  include_tasks: transformSettings.yml
  vars:
    basepath: /opnsense/nat/outbound/rule 
    name: NAT Rule

  loop: "{{ opn_nat }}"
  when: opn_nat is defined

- name: NAT Port Forward
  include_tasks: transformSettings.yml
  vars:
    basepath: /opnsense/nat/rule 
    name: NAT Port Forward

  loop: "{{ opn_nat_port_forward }}"
  when: opn_nat_port_forward is defined

- name: NAT One2One
  include_tasks: transformSettings.yml
  vars:
    basepath: /opnsense/nat/onetoone 
    name: NAT Port Forward

  loop: "{{ opn_nat_onetoone }}"
  when: opn_nat_onetoone is defined

...
